### ISSUE TITLE
Pydantic error when submitting requests

### ISSUE THREAD

**Issue by Vince-janv** [Clinical-Genomics/sendmail-container#18]
## Description
The latest docker container doe not work and is throwing a pydantic error.

## Suggested solution
I suggest we lock the pydantic version, until the whole repo has been migrated to pydantic 2

```
Feb 28 14:35:15 cg-prod-services.scilifelab.se podman[4031126]: Traceback (most recent call last):
Feb 28 14:35:15 cg-prod-services.scilifelab.se podman[4031126]:   File "/home/src/app/cg/server/api.py", line 132, in submit_order
Feb 28 14:35:15 cg-prod-services.scilifelab.se podman[4031126]:     result: dict = api.submit(
Feb 28 14:35:15 cg-prod-services.scilifelab.se podman[4031126]:                    ^^^^^^^^^^^
Feb 28 14:35:15 cg-prod-services.scilifelab.se podman[4031126]:   File "/home/src/app/cg/meta/orders/api.py", line 79, in submit
Feb 28 14:35:15 cg-prod-services.scilifelab.se podman[4031126]:     self.ticket_handler.connect_to_ticket(
Feb 28 14:35:15 cg-prod-services.scilifelab.se podman[4031126]:   File "/home/src/app/cg/meta/orders/ticket_handler.py", line 203, in connect_to_ticket
Feb 28 14:35:15 cg-prod-services.scilifelab.se podman[4031126]:     email_form.submit()
Feb 28 14:35:15 cg-prod-services.scilifelab.se podman[4031126]:   File "/usr/local/lib/python3.11/site-packages/sendmail_container/request.py", line 47, in submit
Feb 28 14:35:15 cg-prod-services.scilifelab.se podman[4031126]:     raise HTTPError(f"{response.status_code}: {response.text}")
Feb 28 14:35:15 cg-prod-services.scilifelab.se podman[4031126]: requests.exceptions.HTTPError: 422: {"detail":[{"type":"list_type","loc":["body","attachments"],"msg":"Input should be a valid list","input":{"filename":"order.json","file":{"_file":{},"_max_size":1048576,"_rolled":false,"_TemporaryFileArgs":{"mode":"w+b","buffering":-1,"suffix":null,"prefix":null,"encoding":null,"newline":null,"dir":null}},"size":30569,"headers":{"content-disposition":"form-data; name=\"attachments\"; filename=\"order.json\""}},"url":"https://errors.pydantic.dev/2.5/v/list_type"}]}
```

**Comment by henrikstranneheim** [comment]
Fixed by https://github.com/Clinical-Genomics/sendmail-container/pull/19
